steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/ohiru-no-pekkle:latest','.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/$PROJECT_ID/ohiru-no-pekkle:latest']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: gcloud
  args:
  - run
  - deploy
  - ohiru-no-pekkle
  - --image
  - gcr.io/$PROJECT_ID/ohiru-no-pekkle:latest
  - --region
  - europe-west1
  - --platform
  - managed
images:
- 'gcr.io/$PROJECT_ID/ohiru-no-pekkle:latest'

